# Generated by Django 3.2.16 on 2023-04-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.secteur')),
            ],
        ),
    ]
