# Generated by Django 3.2.16 on 2023-04-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTime_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('lastPrice', models.FloatField(default=0)),
                ('lastVolume', models.FloatField(default=0)),
                ('dayHigh', models.FloatField(default=0)),
                ('dayLow', models.FloatField(default=0)),
                ('open', models.FloatField(default=0)),
                ('previousClose', models.FloatField(default=0)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.societe')),
            ],
        ),
        migrations.CreateModel(
            name='Historical_data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('Open', models.FloatField(default=0)),
                ('High', models.FloatField(default=0)),
                ('Low', models.FloatField(default=0)),
                ('Close', models.FloatField(default=0)),
                ('Volume', models.FloatField(default=0)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.societe')),
            ],
        ),
    ]
