# Generated by Django 3.2.16 on 2023-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_historical_data_realtime_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_data',
            name='Rendement',
            field=models.FloatField(default=0),
        ),
    ]
