# Generated by Django 3.2.16 on 2023-04-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_historical_data_rendement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_data',
            name='Rendement',
        ),
    ]
