# Generated by Django 3.2.16 on 2023-04-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230408_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_data',
            name='Date',
            field=models.DateField(),
        ),
    ]
