# Generated by Django 3.2.16 on 2023-04-03 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar', models.BinaryField(editable=True, null=True)),
                ('d_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('fb_url', models.URLField(max_length=50, null=True)),
                ('twitter_url', models.URLField(max_length=50, null=True)),
                ('linkedin_url', models.URLField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
